[8.0] Adding module purchase_request_type_to_rfq
open-synergy/opnsynid-purchase-workflow pull request #17
Opened 2016-10-26 09:07 UTC by mikevhe18

2016-10-27 23:12 UTC, andhit-r requested changes
Jgn lp rebase. Jgn disquash dulu tp.

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/README.rst
> +1.  Clone the branch 8.0 of the repository https://github.com/OCA/purchase-workflow
open-synergy

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/README.rst
> +.. image:: https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas
Ini buang aja mike, kita ga punya runbot.

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/README.rst
> +<https://github.com/OCA/purchase-workflow/issues>`_. In case of trouble, please
open-synergy

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/README.rst
> +* Odoo Community Association: `Icon <https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.svg>`_.
Buang

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/README.rst
> +.. image:: https://odoo-community.org/logo.png
OpenSynergy Indonesia

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/README.rst
> +This module is maintained by the OCA.
OpenSynergy Indonesia

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/README.rst
> +OCA, or the Odoo Community Association, is a nonprofit organization whose
Buang

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/README.rst
> +To contribute to this module, please visit https://odoo-community.org.
Buang

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/__openerp__.py
> +    'author': 'OpenSynergy Indonesia,Odoo Community Association (OCA)',
Nama kita saja

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/__openerp__.py
> +    'installable': True,
Tambahin auto install

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/wizard/purchase_request_line_make_purchase_order.py
> +from openerp import _
from openerp.tools.translate import _

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/wizard/purchase_request_line_make_purchase_order.py
> +        val = []
val = False

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/wizard/purchase_request_line_make_purchase_order.py
> +                val.append(line.request_id.order_type_id.id)
val = line.order_type_id.id

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/wizard/purchase_request_line_make_purchase_order.py
> +        return val[0]
return val

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/wizard/purchase_request_line_make_purchase_order.py
> +                if line.request_id.order_type_id.id not in val:
if line.order_type_id.id != val

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/wizard/purchase_request_line_make_purchase_order.py
> +            'order_type_id': line.request_id.order_type_id.id
line.order_type_id.id

2016-10-27 23:12 UTC, andhit-r commented on purchase_request_type_to_rfq/wizard/purchase_request_line_make_purchase_order.py
> +    order_type_id = fields.Many2one(
Ini dipakenya dimana?

2016-10-27 23:19 UTC, mikevhe18 commented
@andhit-r oh langsung dibikin open-synergy mas ? Kirain masih dibikin beda commit jadi gue bikin OCA dulu

2016-10-27 23:20 UTC, mikevhe18 commented on purchase_request_type_to_rfq/wizard/purchase_request_line_make_purchase_order.py
> +    order_type_id = fields.Many2one(
ini buat ditampilin di view wizardnya mas, di detailnya

2016-10-27 23:34 UTC, andhit-r commented
Lgs aja mike

2016-10-27 23:39 UTC, andhit-r commented on purchase_request_type_to_rfq/wizard/purchase_request_line_make_purchase_order.py
> +    order_type_id = fields.Many2one(
Oke

2016-10-28 01:09 UTC, andhit-r approved these changes

2016-10-28 01:10 UTC, merged